### ISSUE TITLE
ValueError: segments are not even close to closed

### ISSUE THREAD

**Issue by petterreinholdtsen** [SebKuzminsky/svg2gcode#6] opened 2024-11-24 11:59 UTC
I am trying to generate a patch for a simple sign with negative text in the senter and straight edges enclosing the letters.

I got this error from svg2gcode:

```
Traceback (most recent call last):
  File "/home/pere/src/debian/svg2gcode-upstream/svg2gcode", line 1161, in <module>
    results += handle_operation(op, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pere/src/debian/svg2gcode-upstream/svg2gcode", line 315, in handle_operation
    input_path = gcoder.close_path(input_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pere/src/debian/svg2gcode-upstream/gcoder.py", line 315, in close_path
    (this_seg, next_seg) = join_segments(this_seg, next_seg)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pere/src/debian/svg2gcode-upstream/gcoder.py", line 309, in join_segments
    raise ValueError("segments are not even close to closed: %s, %s" % (this_seg, next_seg))
ValueError: segments are not even close to closed: Line(start=(89.37644166999998+287.69949000000014j), end=(83.34063866999999+287.69949j)), QuadraticBezier(start=(78.40037566999999+283.54471j), control=(79.90932666999998+283.54471j), end=(80.96352466999998+282.88325000000003j))
```

The command used to trigger the error was "svg2gcode --speed 2000 --feed 50 --plunge-feed 2000 --z-cut-depth -0.8  jobfile skilt-smaskebu.svg > skilt-smaskebu.ngc", using the following jobfile content:

```
{
  "jobs": [
    {
      "operations": [
        {
          "offset": {
            "distance": 2,
            "max-depth-of-cut": 0.1,
            "ramp-slope": 0.005,
            "work-holding-tabs": {
              "number-of-tabs": 4,
              "height": 0.3,
              "width": 5
            }
          }
        }
      ]
    }
  ]
}
```

The SVG file is attached.

 ![skilt-smaskebu](https://github.com/user-attachments/assets/edb8e2d1-88ab-42cd-8c94-2e074f60bd26)

Note, the shapes are outside the visible drawing on github.  I've tried different variations of boxes without avoiding the error.

**Comment by SebKuzminsky** [comment] 2024-11-24 18:11
svg2gcode handles most of the file ok, it has problems with paths 6, 9, and 10:
![image](https://github.com/user-attachments/assets/b0e1eb01-b17a-4c09-bc4f-b9498c9f59ec)

**Comment by SebKuzminsky** [comment] 2024-11-24 18:16
The three paths that fail are the "disjoint" ones, ie the ones that include "pen up":
![image](https://github.com/user-attachments/assets/28e2e676-f2ff-4874-aa39-0d77c543a5ce)

**Comment by petterreinholdtsen** [comment] 2024-11-24 18:36
[Sebastian Kuzminsky]
> The three paths that fail are the "disjoint" ones, ie the ones that
> include "pen up":

All the letters were created using Inkscape Path->Object to Path.  No
idea how to avoid this.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SebKuzminsky** [comment] 2024-11-24 18:41
Yeah, it's valid SVG so svg2gcode should accept it.

**Comment by SebKuzminsky** [comment] 2024-11-24 19:19
Got it:
![image](https://github.com/user-attachments/assets/ff975c7c-db04-433b-8c25-79fe5201e9f5)

I had to disable the workholding tabs on the shorter paths, so the job file looks like this:
```
{ 
  "jobs": [
    { 
      "paths": [ 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 14 ],
      "operations": [
        { 
          "offset": {
            "distance": 2,
            "max-depth-of-cut": 0.1,
            "ramp-slope": 0.005,
            "work-holding-tabs": {
              "number-of-tabs": 4,
              "height": 0.3,
              "width": 5
            }
          }
        }
      ]
    },
    { 
      "paths": [ 7, 11, 13 ],
      "operations": [
        {
          "offset": {
            "distance": 2,
            "max-depth-of-cut": 0.1,
            "ramp-slope": 0.005
          }
        }
      ]
    }
  ]
}
```

**Comment by SebKuzminsky** [comment] 2024-11-24 19:21
Fixed in 3479b1a.  Thanks for the very detailed bug report, that made it easier to reproduce and fix!

**Closed as completed by SebKuzminsky** 2024-11-24 19:21 UTC

**Comment by petterreinholdtsen** [comment] 2024-11-24 19:57
[Sebastian Kuzminsky]
> Fixed in 3479b1a.  Thanks for the very detailed bug report, that made
> it easier to reproduce and fix!

Thank you for the quick resolution.  I got it working. :)

Ended up dropping the tabs everywhere, as it is not really needed when I
glue the work piece to the sacrificial plate.  Will test the cut at the
next opportunity. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SebKuzminsky** [comment] 2024-11-24 20:56
May I suggest an alternate method for the edge cut? 

Instead of four overlapping rectangles carefully sized and positioned so that their interior cuts result in freeing the sign from the raw material, draw a single rectangle that matches the actual material contour for the sign exterior.  Then in the job file exclude that path from the "letters" operation and add a new operation for the final edge cut, with a negative offset so it cuts the outside of the path.

**Comment by petterreinholdtsen** [comment] 2024-11-25 07:15
[Sebastian Kuzminsky]
> May I suggest an alternate method for the edge cut?

Thank you.  Very good idea. :)

Btw, how do you identify which shape is which path?  My 'less' and
'inkscape' do not seem to be good tools for this.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SebKuzminsky** [comment] 2024-11-25 13:44
> Btw, how do you identify which shape is which path? My 'less' and 'inkscape' do not seem to be good tools for this.

I don't have a great answer for this question, and that's a bit of a usability problem for this software.  A simple GUI like dxf2gcode has would be great but I suck at writing GUIs.

What I usually do is write a tiny job file that just has an "engrave" operation applied to a single path, and run it over and over with each of the different paths.  Then I inspect the per-path gcode files to see which is which. 

:-/
